### PR TITLE
Update modmail.js 

### PR DESCRIPTION
**Pull request by Krishiv17**
Bot doesn't need Manage Server permissions to Modmail a user, it's dm'ing the user so the only permissions the bot would need would be Read/ Send Messages.

### CODE REVIEW

**Comment by CaesiumSG** [comment]
krishivvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv the bot is depreciated

**Comment by CaesiumSG** [comment]
but thanks nab ur cool bro

**Comment by Krishiv17** [comment]
lmao

**Comment by Krishiv17** [comment]
Modify it in perihelion tho lol

**Comment by CaesiumSG** [comment]
unblock me in discord when

**Review by CaesiumSG — COMMENTED** [review]
ok

**Comment by CaesiumSG** [comment]
ok boomer its done

**Comment by Krishiv17** [comment]
> unblock me in discord when

i didnt block you lmao

**Pull request merged**
